# Generated by Django 5.1.2 on 2024-10-22 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "userId",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("firstName", models.TextField(max_length=100)),
                ("lastName", models.TextField(max_length=100)),
                ("email", models.EmailField(max_length=100, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("SECURITY", "Security"),
                            ("VISITOR", "Visitor"),
                        ]
                    ),
                ),
                ("password", models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Visits",
            fields=[
                (
                    "visitId",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("visit_date", models.DateTimeField()),
                ("check_out_date", models.DateTimeField()),
                ("accepted", models.BooleanField(default=False)),
                (
                    "purpose_of_visit",
                    models.CharField(
                        choices=[
                            ("AUDITION", "Audition"),
                            ("INVITATION", "Invitation"),
                            ("FIELD VISIT", "Field visit"),
                        ]
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visiting_user",
                        to="visitorapp.user",
                    ),
                ),
            ],
        ),
    ]
