# Generated by Django 5.1.2 on 2024-10-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visitorapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="firstName",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="lastName",
            field=models.CharField(max_length=100),
        ),
    ]
