# Generated by Django 5.1.2 on 2024-10-22 14:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visitorapp", "0002_alter_user_firstname_alter_user_lastname"),
    ]

    operations = [
        migrations.AddField(
            model_name="visits",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="firstName",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="lastName",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("SECURITY", "Security"),
                    ("VISITOR", "Visitor"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="visits",
            name="purpose_of_visit",
            field=models.CharField(
                choices=[
                    ("AUDITION", "Audition"),
                    ("INVITATION", "Invitation"),
                    ("FIELD VISIT", "Field visit"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="visits",
            name="visit_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
