# Generated by Django 5.1.2 on 2024-10-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visitorapp", "0003_visits_status_alter_user_firstname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="firstName",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="lastName",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=200),
        ),
    ]
