# Generated by Django 5.1.2 on 2024-11-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visitorapp", "0004_alter_user_firstname_alter_user_lastname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visits",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=10,
                null=True,
            ),
        ),
    ]
